/* Generated by the LVCpp Generator */


#include "test_h_file.h"

 /*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*\
 *      Do not Touch Headers Below       *
 * Generated by Bills CPP file generator *
 \*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*/
using ::myclass;


myclass::myclass(){


}

void myclass::func1(){


}

int myclass::func2(){

	skfaj;skdfa
	asldkfja;sdj

}

double myclass::func3(double i){
tewtsdasdfasdfasd
asdfasdf
}


