/* Generated by the LVCpp Generator */


#include "test_h_file.h"

 /*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*\
 *      Do not Touch Headers Below       *
 * Generated by Bills CPP file generator *
 \*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*/
using ::myclass;


 myclass::myclass(){


}

void myclass::func1(){

wrqwe
}

double myclass::func2(){

wqrqwerqwreq
}

double myclass::func3(double i){

qwerqweerqewqrqwerq
}


