/* Generated by the LVCpp Generator */


#include "test_h_file.h"

 /*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*\
 *      Do not Touch Headers Below       *
 * Generated by Bills CPP file generator *
 \*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*/
using ::myclass;


void myclass::func1(){

testing 123
}

const std::string& myclass::func2(){


}

double myclass::func3(double i){


}


