/* Generated by the LVCpp Generator */


#include "../CppParlexser/plexser.h"

 /*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*\
 *      Do not Touch Headers Below       *
 * Generated by Bills CPP file generator *
 \*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*/

 plexser::plexser(){


}

 plexser::plexser(const std::string& file){


}

 plexser::plexser(std::ifstream* i){


}

 plexser::~plexser(){


}

void plexser::setFstream(const std::string& file){


}

std::vector<cppclass>* plexser::getClasses(){


}

std::string plexser::getFileName(){


}

void plexser::tokenize(){


}

void plexser::initializeKeywords(){


}

void plexser::initializeOperators(){


}

void plexser::initializePreProc(){


}

void plexser::eatWhiteSpace(){


}

void plexser::eatComments(){


}

void plexser::NonGenerated(char first){


}

void plexser::buildFuncHeader(char first, std::pair<std::string,char> cur){


}

void plexser::postProcess(){


}

void plexser::setFuncInfo(memfunc& f){


}

void plexser::setParamList(memfunc& f){


}

void plexser::setConst(memfunc& f){


}

void plexser::setBody(memfunc& f){


}

char plexser::getChar(){


}

cppclass& plexser::getClass(const std::string& name){


}

std::pair<std::string,char> plexser::nextToken(char first){


}


