/* Generated by the LVCpp Generator */


#include "testhfile2.h"

 /*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*\
 *      Do not Touch Headers Below       *
 * Generated by Bills CPP file generator *
 \*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*/

 plexser::plexser(){


}

 plexser::plexser(const std::string& file){


}

 plexser::plexser(std::ifstream* i){


}

void plexser::setFstream(const std::string& file){


}

std::string plexser::getFileName(){


}

void plexser::tokenize(){


}

void plexser::initializeKeywords(){


}

void plexser::initializeOperators(){
aslkdjf;lasd
asdfk;lajsf

asdlfjaslkfj

}

void plexser::initializePreProc(){


}

void plexser::eatWhiteSpace(){


}

void plexser::eatComments(){


}

void plexser::NonGenerated(char first){


}

void plexser::postProcess(){


}

void plexser::setFuncInfo(memfunc& f){


}

void plexser::setParamList(memfunc& f){


}

void plexser::setConst(memfunc& f){


}

void plexser::setBody(memfunc& f){


}

char plexser::getChar(){


}

cppclass& plexser::getClass(const std::string& name){


}


