/* Generated by the LVCpp Generator */


#include "testhfile.h"
using tokens::no_class;



using tokens::second_class;

const std::string& second_class::helloworld(int x, int y){


}

int[] second_class::asdlfkjlsd(const double amp, sometype* should_crash){


}



using tokens::my_class;

const std::string& my_class::helloworld(int x, int y = 0){


}

std::string my_class::hieric(double amp, sometype should_crash = "hello world"){


}



